### ISSUE TITLE
Quick Edit / AJAX Conflict

### ISSUE THREAD

**Issue by MissAmy** [ConnorWiseman/jcink-custom-structure#1]
When using the custom post module, the Quick Edit function is no  longer functional, requiring it to be turned off for the entire board to allow users to edit their posts. The button is clickable, and without the posting module functions properly, but there is no area in which to edit the post after clicking on the button for editing.

**Comment by ConnorWiseman** [comment]
With how busy I've been, I almost didn't see this!

I'm aware of this problem and am nearly finished with an update that will provide a built-in alternative to Jcink's quick editor. There's a monkey-patched replacement available [in this topic](http://code.jcink.net/?showtopic=361#entry1511) that ought to fit your needs until I can roll out 1.6.

Thank you for doing your best to bring this to my attention!

**Comment by ConnorWiseman** [comment]
As of version 1.6.0 released this morning, an alternative to the default quick editor is available directly through the script. Please see the documentation for details.

Thank you!
