### ISSUE TITLE
Board Key things don't work

### ISSUE THREAD

**Issue by yunotheninetales** [ConnorWiseman/jcink-custom-structure#2]
I tried putting the users stats with the board stats and it didn't allow it. , etc. broke the CFS.

**Comment by ConnorWiseman** [comment]
`<!-- |avatar| -->` in particular is the global wrapper variable that's causing things to break in your situation. When the parser John wrote for the Board Wrappers iterates over `<!-- |avatar| -->`, its output uses single quotes around attributes. The sample output below was taken from my testing forum, but the principle is illustrated plainly:

``` html
<img src='https://pbs.twimg.com/profile_images/575848008144678912/zt75L8kP_bigger.png' border='0' width='64' height='64' alt='' />
```

To use the `<!--- |avatar| -->` global wrapper variable and any other wrapper variables that may potentially contain single quotes with the Custom Structure script, you will have to switch from using single quotes around the `html` property of the object being passed to the `initialize()` method and use double quotes instead. This is a restriction imposed by the board software and not this script, so there's nothing really I can do about it.

A demonstration of a working `<!--- |avatar| -->` global wrapper variable in the output of the custom statistics module is available on [my testing forum](http://cfs2.jcink.net/#new-statistics). The page source shows how I was able to accomplish it.
