### ISSUE TITLE
no fields in custom posts?

### ISSUE THREAD

**Issue by alida19** [ConnorWiseman/jcink-custom-structure#4]
Sorry if this isn't the right place for this, but I was wondering if it was possible to use custom profile fields in the custom post markup, similar to how they're used in the custom profile markup and mini profiles? If not, could there possibly be some alternative to this? Thank you!

**Comment by ConnorWiseman** [comment]
Sorry I didn't see this! Been busy at school.

This isn't available with this script, but it's a built-in feature of Jcink's using `<!– |field_#| –>` placeholders: http://jcink.com/main/wiki/jfb-skinning-profile-templates

**Comment by alida19** [comment]
no problem! sorry, i've basically just been trying to do a mini profile
that sits on the side of the post and on top of the post as well (like this
for example: http://chemistryrp.jcink.net/?showtopic=14 )? but everything
i've tried just hasn't worked. when it's all in the mini profile area, the
post content area is pushed out of the way. so i put the top mini profile
portion in the board wrappers which worked, but neither jcink's nor your
field placeholders worked in the board wrappers? so i was wondering if i
was doing something wrong and they'll work in the custom post portion or if
i just need to figure out how to make it work in the mini profile.
it's ok if you don't have the answer or anything i just figured i'd try!
thanks so much!

**Comment by ConnorWiseman** [comment]
I think they have to be enabled before they'll appear in miniprofiles:

> If you intend to use your own custom fields, be sure to set: “Enable use of Custom Profile Field variables in templates? Required to use <!– |field_#| –> variables.” to “Yes”.
