### ISSUE TITLE
Custom topics of active topics search

### ISSUE THREAD

**Issue by shounenprotagrl** [ConnorWiseman/jcink-custom-structure#5]
To my understanding, the markup of custom topics would also be the same for the active topics search. But the active search topics isn't changing.

Custom topics: http://gepetto.jcink.net/index.php?showforum=1
Active search topics: http://i.imgur.com/ZAOVaPN.png

**Comment by ConnorWiseman** [comment]
I originally introduced this as default behavior, but opted to change it after I received a few complaints from folk who didn't want their active topics list changed in any way. At the moment this feature has to be manually enabled through [an extra setting](https://github.com/ConnorWiseman/jcink-custom-structure#custom-topics-configuration-reference), `activeTopics`, which must be set to `true` to turn it on.

The code would look something like...

```
customTopics.initialize({
    config: {
        activeTopics: true
    },
    html: '...'
});    
```
