### ISSUE TITLE
User group color prefix/suffix?

### ISSUE THREAD

**Issue by fireinthedisco** [ConnorWiseman/jcink-custom-structure#6]
Thanks much for this script. I'm working on custom profiles. I'd very much like to see the IBStore currency be able to be used - as the other issue brings up, so I understand it's not currently possible. Other than that, is there any way to access the group color prefix and suffix, so you can color a group name?

**Comment by ConnorWiseman** [comment]
If the prefix or suffix don't appear in the raw page markup- and recalling from memory, user profiles are like topic/post search results in that I don't think they support either prefixes or suffixes on usernames- then it's not directly possible using this script, no.

What I might advise doing instead is just using the group name as a CSS class and styling it that way:

``` JavaScript
customProfile.initialize({
   html: '<span class="{{userGroup}}">Username</span>'
});
```

``` css
.usergroup {
    color: #00aa00;
}
```
