### ISSUE TITLE
custom post issue

### ISSUE THREAD

**Issue by malinhanak** [ConnorWiseman/jcink-custom-structure#9]
I'm experiencing some issue with the custom post, I have finally gotten the  to work but I can't get any miniprofile field like  or  to work, what am I doing wrong, because as far as I can see an understand they are suppose to work right?

**Comment by ConnorWiseman** [comment]
As far as I know, those two are tied to internal settings in Jcink's administrator control panel.
1. `<!-- |status| -->` only functions if **System Settings** -> **Topics, Posts, & Polls** -> **Show online/offline status in posts?** is set to yes.
2. The `<!-- |field_#| -->` variables only function if **Skins & Templates** -> **Profile Templates** -> **Enable use of Custom Profile Field variables in templates? Required to use  variables.** is set to yes.
